name             'test-cookbook'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures test-cookbook'
long_description 'Installs/Configures test-cookbook'
version          '0.1.0'
